### PR TITLE
Proofreading front page (363 words)

### PR DESCRIPTION
**Pull request by johndotpage**
Addressing issue #4

### CODE REVIEW

**Comment by johndotpage** [comment]
@yegor256 just a nudge that you've not accepted this yet.

**Comment by 0crat** [comment]
This pull request [#5](https://github.com/zerocracy/audit.zerocracy.com/issues/5) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/0b53973d-8749-4e75-881f-c75fbcd5aff3); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by carlosmiranda** [comment]
@johndotpage no comments. Thanks

**Comment by carlosmiranda** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@g4s8 can we merge this?

**Comment by g4s8** [comment]
@yegor256 please check this PR

**Comment by carlosmiranda** [comment]
@yegor256 ping

**Comment by carlosmiranda** [comment]
@yegor256 ping. This has been on my queue for a while now.

**Comment by yegor256** [comment]
@johndotpage thanks!

**Comment by 0crat** [comment]
Job [#5](https://github.com/zerocracy/audit.zerocracy.com/issues/5) is not in the agenda of @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), can't retrieve data and time of add

**Comment by 0crat** [comment]
Code review was too long (68 days), architects (@g4s8) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
Job [#5](https://github.com/zerocracy/audit.zerocracy.com/issues/5) is not in the agenda of @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#5](https://github.com/zerocracy/audit.zerocracy.com/issues/5) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by johndotpage** [comment]
@sereshqua What?

**Comment by johndotpage** [comment]
@sereshqua Can you explain why the quality was bad please?

**Comment by sereshqua** [comment]
@johndotpage no issues were found during the CR, this leads to bad quality :)

I am curious why you are so worried about @carlosmiranda, cause I was evaluating his work :D

**Comment by johndotpage** [comment]
@sereshqua Er, okay. Sorry. I assumed it was a reflection on the "Job Performer". So @carlosmiranda found no issues during the "code" review so the quality of the review must be bad? Interesting. I shall make sure I get something wrong next time so that the reviewer can get some credit. :D

**Pull request merged**
